services:
  template-python:
    container_name: template-python
    build:
      context: .
      dockerfile: Dockerfile
    image: ks6088ts/template-python:local
    command: ["python", "-m", "template_python.core"]
    env_file:
      - .env
    environment:
      PROJECT_NAME: hello
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: "no"
