name: test

on:
  push:
    branches:
      - "main"
      - "feature/**"
      - "copilot/**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        platform:
          - "ubuntu-latest"
        python-version:
          - "3.13"
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        shell: bash
        run: pipx install uv
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run CI tests
        shell: bash
        run: |
          make ci-test
          make ci-test-docs
